apiVersion: batch/v1
kind: Job
metadata:
  name: initializer
spec:
  template:
    spec:
      containers:
        - name: initializer
          image: nikmohan81/initializer
      restartPolicy: Never
  backoffLimit: 2

