apiVersion: batch/v1
kind: Job
metadata:
  name: initializer
spec:
  template:
    spec:
      containers:
        - name: initializer
          image: nikmohan81/initializer
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
      restartPolicy: Never
  backoffLimit: 2

