spring:
  profiles:
    active: prod

---

spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hourglass

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      host: hourglassdb-service
      port: 27017
      database: hourglass
